quarkus:
  token: abc
  http:
    port: 8080
    test-port: 8085
    cors: false
  swagger-ui:
    always-include: true
    path: /swagger
  mongodb:
    database: quarkus
    connection-string: ${MONGODB_CONNECTION_STRING:mongodb://root:root@localhost:27017/quarkus?authSource=admin}
    username: ${MONGO_INITDB_ROOT_USERNAME:root}
    password: ${MONGO_INITDB_ROOT_PASSWORD:root}
  log:
      enable: true
      level: INFO
      color: true
mp:
  openapi:
    scan:
      disabled: true